- type: reagentProductionType
  id: CumProduction
  reagent: Cum
  solutionName: balls
  maximumCapacity: 30
  maximumLoad: 10
  unitsPerProduction: 5
  dryPopup: cum-verb-dry
  successPopup: cum-verb-success

- type: reagentProductionType
  id: BreastMilkProduction
  reagent: Milk
  solutionName: breasts
  maximumCapacity: 50
  maximumLoad: 5
  fillTime: 1
  unitsPerProduction: 5
  dryPopup: milk-verb-dry
  successPopup: milk-verb-success

- type: reagentProductionType
  id: SquirtProduction
  reagent: NaturalLubricant
  solutionName: pussy
  maximumCapacity: 10
  maximumLoad: 2
  unitsPerProduction: 4
  dryPopup: squirt-verb-dry
  successPopup: squirt-verb-success

- type: reagentProductionType
  id: HoneyProduction
  reagent: Honey
  solutionName: honeyStomach
  maximumCapacity: 50
  maximumLoad: 5
  fillTime: 1
  unitsPerProduction: 5
  dryPopup: honey-verb-dry
  successPopup: honey-verb-success
